In [42]:
# import des librairies requises
import pandas as pd
import unicodedata
import re
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from stop_words import get_stop_words

In [67]:
# lecture des différents csv dans les 3 variables 
#df1 = pd.read_csv("./../data/offers.csv")
df1 = pd.read_csv("./../data/offers_with_10k_each_contracts.csv")

#df2 = pd.read_csv("./../data/organizations.csv")
#df3 = pd.read_csv("./../data/recruiters.csv")

df1
# df2
# df3

offer_id                                              title  \
0        620861           Développeur(euse) Android expérimenté(e)   
1        620862                                Ingénieur QA Mobile   
2        330503  Vérificateur Documents Techniques Aéronautique...   
3        623978                             Chef de Produit Mobile   
4        391895                                   Ordonnanceur H/F   
5        626090                      Consultant stratégie digitale   
6        612987           Ingénieur études et développement C# H/F   
7        358977  RESPONSABLE BUREAU D'ÉTUDES CÂBLAGE ELECTRIQUE...   
8        694642                         Responsable Ingénierie QOS   
9        565156                               Sales Representative   
10       612657                            Ingénieur de Production   
11       330873    UN RESPONSABLE ASSURANCE QUALITE PRODUCTION H/F   
12       612735       Assistant(e) Chef de projet digital RH (H/F)   
13       696375             Collaborateur comptable bilingue (H/F)   
14       613438                          Product Owner - Data Team   
15       679460                      Technico-commercial industrie   
16       364408  Responsable Commercial E-SANTE Languedoc-Rouss...   
17       679069  TECHNICIEN SUPERIEUR RESEAUX INFORMATIQUES ET ...   
18       161711                 Adjoint au Directeur Qualité (H/F)   
19       683695                           Comptable en Cabinet H/F   
20       162284                           MANAGER SUPPLY CHAIN H/F   
21       616315     STAGE Ingénieur études et développement BI H/F   
22       619811                TECHNICIEN CONCEPTION OUTILLAGE H/F   
23       616309                    Ingénieur Développement C++ H/F   
24       366539  Attaché Commercial (Profil Chasseur) H/F - Her...   
25       679828            2 COLLABORATEURS COMPTABLE en cdi (H/F)   
26       625338                           Ingénieur commercial H/F   
27       330887                                H/F Responsable QSE   
28       621522                   Développeur android confirmé H/F   
29       616327                     Ingénieur Développeur Java H/F   
...         ...                                                ...   
38464    617926               Job saisonnier - Vendeur conseil H/F   
38465    616081                               Business Analyst H/F   
38466    613056         Chargé de recrtuement / Business Developer   
38467    617002                   Assistant Fusion et Acquisition    
38468    617008                   Conseiller Spécialisé Entreprise   
38469    616960                ADJOINT MANAGER STATION-SERVICE H/F   
38470    613417                     MANAGER STATION DE SERVICE H/F   
38471    616840     Ingénieur Etudes et Développement Java/J2E H/F   
38472    613459                 Ingénieur Réseaux N2/N3 - 24/7 H/F   
38473    677153                       Agent Immobilier Indépendant   
38474    612738                                 BtoB Sales Manager   
38475    617368                          Junior PMO/AMOA projet SI   
38476    617350                                Community developer   
38477    626176  KUZZLE - BUSINESS DEVELOPER / SALES & MARKETIN...   
38478    658018  Development Engineer Sensors, Electronics and ...   
38479    614755                       Assistant(e) Chef de Produit   
38480    612600                                Business Developer    
38481    617530                  Ingénieurs d'affaires ESN - SSII    
38482    616894                                Créatif / Graphiste   
38483    612792                               Ingénieur Commercial   
38484    617578                           DEVELOPPEUR BACK END H/F   
38485    613297                                      Acheteurs H/F   
38486    615913                                          DIRECTEUR   
38487    673150       Analyste Cyber-sécurité H/F - VIE Luxembourg   
38488    613345                            Country Supply Lead H/F   
38489    613543  

In [44]:
df_offers = df1[df1.contract_id.notnull()]

In [45]:
df1.contract_id.value_counts()

3    10000
2    10000
1    10000
4     4800
5     3694
Name: contract_id, dtype: int64

In [46]:
# Remplacer les valeurs NA avec ""

df_offers['description'] = [BeautifulSoup(text, "html.parser").get_text() for text in df_offers['description'].fillna("")]

In [47]:
import unidecode

In [48]:
def my_preprocessor(text):
    return unidecode.unidecode(''.join([letter for letter in text if not letter.isdigit()]).strip().lower())

In [49]:
# Vectorisation

from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer


#stop words fr dans stop_words
stop_wordsFR = get_stop_words('french')

vectorizer = TfidfVectorizer(
    ngram_range=(1, 3),
    analyzer="word",
    binary=False,
    max_features=6000,
    stop_words = stop_wordsFR,
preprocessor=my_preprocessor)


In [50]:
#tfidf fit de cleaned_description

vectorizer.fit(df_offers.description)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=6000, min_df=1,
        ngram_range=(1, 3), norm='l2',
        preprocessor=<function my_preprocessor at 0x0DD2B270>,
        smooth_idf=True,
        stop_words=['a', 'ai', 'aie', 'aient', 'aies', 'ait', 'alors', 'as', 'au', 'aucun', 'aura', 'aurai', 'auraient', 'aurais', 'aurait', 'auras', 'aurez', 'auriez', 'aurions', 'aurons', 'auront', 'aussi', 'autre', 'aux', 'avaient', 'avais', 'avait', 'avant', 'avec', 'avez', 'aviez', 'avions', 'avoir', '...ça', 'étaient', 'étais', 'était', 'étant', 'état', 'étiez', 'étions', 'été', 'étés', 'êtes', 'être'],
        strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [68]:
X = vectorizer.transform(df_offers.description)
X

<38494x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 4244783 stored elements in Compressed Sparse Row format>

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test= train_test_split(X, df_offers.contract_id, test_size=0.30)

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
clf = LogisticRegression()

In [56]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [57]:
from collections import Counter

In [58]:
Counter(clf.predict(X_test))

Counter({1: 3878, 3: 3322, 2: 3165, 4: 761, 5: 423})

In [59]:
Counter(y_test)

Counter({2: 3055, 3: 3032, 4: 1436, 1: 2899, 5: 1127})

In [60]:
print("Matrice de confusion : \n", confusion_matrix(y_test, clf.predict(X_test)))

Matrice de confusion : 
 [[2159  503   91   80   66]
 [ 663 2110   92  132   58]
 [  49   36 2915   27    5]
 [ 519  290  156  375   96]
 [ 488  226   68  147  198]]


In [61]:
xArray = X[:10].toarray()

In [78]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [79]:
#Score de la prédiction
accuracy_score(clf.predict(X_test), y_test)

0.6716598839726383

In [124]:
 print(classification_report(clf.predict(X_test), y_test))

             precision    recall  f1-score   support

          1       0.74      0.56      0.64      3878
          2       0.69      0.67      0.68      3165
          3       0.96      0.88      0.92      3322
          4       0.26      0.49      0.34       761
          5       0.18      0.47      0.26       423

avg / total       0.74      0.67      0.70     11549



In [125]:
xArray

array([[0.06200716, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05849331, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.19095715],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [63]:
from sklearn.pipeline import Pipeline

In [64]:
pipeline = Pipeline(steps=[
    ('text_extraction', vectorizer),
    ('classifier', LogisticRegression())
])

In [65]:
#pipeline.fit(....)

In [66]:
#pipeline.predict(.....)