In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

import sklearn
from sklearn.linear_model import LogisticRegression
#from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
#Import du fichier
AA = pd.read_csv("./../data/offers.csv", encoding='utf-8')
AA

title  \
0               Commercial B2B Solutions Print (75) F/H   
1     Chargé de relation client - vente d'évènements...   
2                          Ingénieur Commercial IDF F/H   
3              Account Manager Media Payant - CDI - F/H   
4               Responsable Grand Compte Groupe PSA F/H   
5                     Ingénieur Technico-Commercial F/H   
6     Business Developer / Chargé de Partenariat - U...   
7                                    KAM AUTOMOBILE F/H   
8          Ingénieur Technico-Commercial impression F/H   
9                   Assistant Responsable d'Affaire F/H   
10                              TECHNICO-COMMERCIAL F/H   
11                         1 RESPONSABLE DE SECTEUR F/H   
12    INGENIEUR TECHNICO-COMMERCIAL ILE-DE-FRANCE ÉQ...   
13                   Directeur Business Development F/H   
14                  TECHNICO-COMMERCIAL - EPI - IDF F/H   
15                       Senior Manager 'Paiements' F/H   
16                              Key Account Manager F/H   
17                               BUSINESS DEVELOPER F/H   
18                             Attaché commercial - F/H   
19                           BUSINESS UNIT DIRECTOR F/H   
20                 business developer international F/H   
21                          Commercial grand compte F/H   
22               Gestionnaire Copropriété Tertiaire F/H   
23           Consultant en transformation numérique F/H   
24              Ingénieur commercial grands comptes F/H   
25                                       Commercial F/H   
26    COMMERCIAL(E) INTINERANT(E) EN AGENCEMENT D'ES...   
27                                  Chef des ventes F/H   
28                             Ingénieur d'affaires F/H   
29                            Commercial sédentaire F/H   
...                                                 ...   
9970   Spécialiste Qualité - Contrôle extérieur - Gé...   
9971                                Auditeur Sénior H/F   
9972  INGENIEUR CONTROLE TECHNIQUE CONSTRUCTION EN A...   
9973  Stage Ingénieur - Développement d'un démonstra...   
9974                chef de rayon Fruits et Légumes H/F   
9975                         Contrôleur permanent (H/F)   
9976                     CHEF DE RAYON POISSONNERIE H/F   
9977           CHEF DE RAYON BOULANGERIE PATISSERIE H/F   
9978                         CHEF DE RAYON FRAIS LS H/F   
9979  Stage Ingénieur - Super Tanker  - Requirements...   
9980    Stage Ingénieur - Super Tanker - Functional H/F   
9981      Stage Ingénieur - Super Tanker - Méthodes H/F   
9982                COMPTABLE COLLABORATEUR CABINET h/f   
9983               STAGIAIRE AU SECRETARIAT GENERAL F/H   
9984         Chargé(e) d'affaires BTP confirmé(e) (F/H)   
9985                     RESPONSABLE D'AGENCE - ORLÉANS   
9986                Conducteur de travaux fibre optique   
9987                                     Ingénieur FTTH   
9988       Ingénieur Etudes de Prix Travaux Publics H/F   
9989                  Ingénieur Qualité Génie Civil H/F   
9990                   Assistant Ingénieur Géomètre H/F   
9991  Assistant Conducteur de Travaux Déconstruction...   
9992          Assistant Conducteur de Travaux Route H/F   
9993      RESPONSABLE DE CABINET DE COACHING DIETETIQUE   
9994                  DIRECTEUR D'AGENCE RH - NIMES H/F   
9995        CONSULTANT EN EVOLUTION PROFESSIONNELLE H/F   
9996                       DIRECTEUR DE SUPERMARCHÉ H/F   
9997           DIRECTEUR ADJOINT DE SUPERMARCHÉ BIO H/F   
9998          COMMERCIAL MARÉE ET FRUITS ET LÉGUMES H/F   
9999               DIRECTEUR ADJOINT DE SUPERMARCHÉ H/F   

                                            description  contract_id  \
0     <p>Au sein de votre agence régionale, vous com...          1.0   
1     <p>Au sein d’une structure de 8 personnes et d...          1.0   
2     <p>Sur un marché d’avenir à forte croissance, ...          1.0   
3     <p>**Intégré à l’équipe Paid Media**, vous aur...          1.0   
4     <p>Principales responsabi

In [137]:
#AA.department_id.fillna(101.0).value_counts()

In [3]:
dataset = AA

#dataset = AA.dropna(axis=0, how='any')           #Suppression des lignes qui contiennent une valeur 'Nan'

In [3]:
import sklearn

In [143]:
sklearn.__version__

'0.19.1'

In [ ]:
from sklearn.impute import SimpleImputer

AA = AA.sample(frac=1).reset_index(drop=True)
AA = AA.head(500)

imp = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imp.fit_transform(AA)

AA['target'] = AA['contract_id']          #Création d'une nouvelle colonne
AA.head()

In [6]:
AA

title  \
0               Commercial B2B Solutions Print (75) F/H   
1     Chargé de relation client - vente d'évènements...   
2                          Ingénieur Commercial IDF F/H   
3              Account Manager Media Payant - CDI - F/H   
4               Responsable Grand Compte Groupe PSA F/H   
5                     Ingénieur Technico-Commercial F/H   
6     Business Developer / Chargé de Partenariat - U...   
7                                    KAM AUTOMOBILE F/H   
8          Ingénieur Technico-Commercial impression F/H   
9                   Assistant Responsable d'Affaire F/H   
10                              TECHNICO-COMMERCIAL F/H   
11                         1 RESPONSABLE DE SECTEUR F/H   
12    INGENIEUR TECHNICO-COMMERCIAL ILE-DE-FRANCE ÉQ...   
13                   Directeur Business Development F/H   
14                  TECHNICO-COMMERCIAL - EPI - IDF F/H   
15                       Senior Manager 'Paiements' F/H   
16                              Key Account Manager F/H   
17                               BUSINESS DEVELOPER F/H   
18                             Attaché commercial - F/H   
19                           BUSINESS UNIT DIRECTOR F/H   
20                 business developer international F/H   
21                          Commercial grand compte F/H   
22               Gestionnaire Copropriété Tertiaire F/H   
23           Consultant en transformation numérique F/H   
24              Ingénieur commercial grands comptes F/H   
25                                       Commercial F/H   
26    COMMERCIAL(E) INTINERANT(E) EN AGENCEMENT D'ES...   
27                                  Chef des ventes F/H   
28                             Ingénieur d'affaires F/H   
29                            Commercial sédentaire F/H   
...                                                 ...   
9970   Spécialiste Qualité - Contrôle extérieur - Gé...   
9971                                Auditeur Sénior H/F   
9972  INGENIEUR CONTROLE TECHNIQUE CONSTRUCTION EN A...   
9973  Stage Ingénieur - Développement d'un démonstra...   
9974                chef de rayon Fruits et Légumes H/F   
9975                         Contrôleur permanent (H/F)   
9976                     CHEF DE RAYON POISSONNERIE H/F   
9977           CHEF DE RAYON BOULANGERIE PATISSERIE H/F   
9978                         CHEF DE RAYON FRAIS LS H/F   
9979  Stage Ingénieur - Super Tanker  - Requirements...   
9980    Stage Ingénieur - Super Tanker - Functional H/F   
9981      Stage Ingénieur - Super Tanker - Méthodes H/F   
9982                COMPTABLE COLLABORATEUR CABINET h/f   
9983               STAGIAIRE AU SECRETARIAT GENERAL F/H   
9984         Chargé(e) d'affaires BTP confirmé(e) (F/H)   
9985                     RESPONSABLE D'AGENCE - ORLÉANS   
9986                Conducteur de travaux fibre optique   
9987                                     Ingénieur FTTH   
9988       Ingénieur Etudes de Prix Travaux Publics H/F   
9989                  Ingénieur Qualité Génie Civil H/F   
9990                   Assistant Ingénieur Géomètre H/F   
9991  Assistant Conducteur de Travaux Déconstruction...   
9992          Assistant Conducteur de Travaux Route H/F   
9993      RESPONSABLE DE CABINET DE COACHING DIETETIQUE   
9994                  DIRECTEUR D'AGENCE RH - NIMES H/F   
9995        CONSULTANT EN EVOLUTION PROFESSIONNELLE H/F   
9996                       DIRECTEUR DE SUPERMARCHÉ H/F   
9997           DIRECTEUR ADJOINT DE SUPERMARCHÉ BIO H/F   
9998          COMMERCIAL MARÉE ET FRUITS ET LÉGUMES H/F   
9999               DIRECTEUR ADJOINT DE SUPERMARCHÉ H/F   

                                            description  contract_id  \
0     <p>Au sein de votre agence régionale, vous com...          1.0   
1     <p>Au sein d’une structure de 8 personnes et d...          1.0   
2     <p>Sur un marché d’avenir à forte croissance, ...          1.0   
3     <p>**Intégré à l’équipe Paid Media**, vous aur...          1.0   
4     <p>Principales responsabi

In [98]:
feature = ["department_id" , "industry_id"]

features = dataset[feature] 
target = dataset['target']

In [122]:
#Discrimination bayésienne 

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model impot
from sklearn.cross_validation import ShuffleSplit, train_test_split

features_train, features_test, target_train, target_test = train_test_split(features, target)

clf = MultinomialNB(alpha=0.1, fit_prior=True)
clf.fit(features_train, target_train)
print('Score = ', clf.score(features_test, target_test))

Score =  0.8237273874631889


In [120]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import ShuffleSplit, train_test_split

clf = MultinomialNB(alpha=0.1)
clf.fit(features, target)
print('Score = ', clf.score(features, target))

Score =  0.8303533866217921


In [124]:
print(classification_report(target_test, clf.predict(features_test)))

             precision    recall  f1-score   support

        1.0       0.82      1.00      0.90      1958
        2.0       0.00      0.00      0.00       206
        3.0       0.00      0.00      0.00       198
        4.0       0.00      0.00      0.00        13
        5.0       0.00      0.00      0.00         2

avg / total       0.68      0.82      0.74      2377



C:\Users\Marine\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [127]:
#Régression logistique

cls = LogisticRegression() 
cls.fit(features_train, target_train)
predictions = cls.predict(features_test)
cls.intercept_
cls.coef_
print(confusion_matrix(target_test, predictions))

[[1958    0    0    0    0]
 [ 206    0    0    0    0]
 [ 198    0    0    0    0]
 [  13    0    0    0    0]
 [   2    0    0    0    0]]


**PROBLEME**

Le modèle prend toujours 1.0 en valeur puisqu'en prenant cette valeur il a très peu de chance de se tromper. En effet, sur 10 000 offres, 8 000 sont des CDI (soit 1.0).