In [138]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [139]:
#Import du fichier
AA = pd.read_csv("./../data/offers.csv", encoding='utf-8')
AA.head()

title  \
0            Commercial B2B Solutions Print (75) F/H   
1  Chargé de relation client - vente d'évènements...   
2                       Ingénieur Commercial IDF F/H   
3           Account Manager Media Payant - CDI - F/H   
4            Responsable Grand Compte Groupe PSA F/H   

                                         description  contract_id  \
0  <p>Au sein de votre agence régionale, vous com...          1.0   
1  <p>Au sein d’une structure de 8 personnes et d...          1.0   
2  <p>Sur un marché d’avenir à forte croissance, ...          1.0   
3  <p>**Intégré à l’équipe Paid Media**, vous aur...          1.0   
4  <p>Principales responsabilités :</p><ul><li>Id...          1.0   

   recruiter_id  department_id  industry_id               location   latitude  \
0         21587          101.0         16.0  Paris 01 - 75, France  48.862903   
1         21587          101.0          9.0  Paris 09 - 75, France  48.877906   
2         21587          101.0          9.0  Paris 05 - 75, France  48.842172   
3         21587          101.0         19.0  Paris 11 - 75, France  48.857993   
4         21587          101.0         15.0  Paris 01 - 75, France  48.862903   

   longitude                  created_at  
0   2.335955  2018-03-28 12:46:34.408753  
1   2.337972  2018-03-28 12:46:34.018429  
2   2.350580  2018-03-28 12:46:33.604334  
3   2.381153  2018-03-28 12:46:33.131170  
4   2.335955  2018-03-28 12:46:31.997686

In [137]:
#AA.department_id.fillna(101.0).value_counts()

In [140]:
dataset = AA

#dataset = AA.dropna(axis=0, how='any')           #Suppression des lignes qui contiennent une valeur 'Nan'

In [142]:
import sklearn

In [143]:
sklearn.__version__

'0.19.1'

In [149]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imp.fit_transform(dataset)

dataset['target'] = dataset['contract_id']          #Création d'une nouvelle colonne
dataset.head()

ImportError: cannot import name '_object_dtype_isnan'

In [98]:
feature = ["department_id" , "industry_id"]

features = dataset[feature] 
target = dataset['target']

In [122]:
#Discrimination bayésienne 

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model impot
from sklearn.cross_validation import ShuffleSplit, train_test_split

features_train, features_test, target_train, target_test = train_test_split(features, target)

clf = MultinomialNB(alpha=0.1, fit_prior=True)
clf.fit(features_train, target_train)
print('Score = ', clf.score(features_test, target_test))

Score =  0.8237273874631889


In [120]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import ShuffleSplit, train_test_split

clf = MultinomialNB(alpha=0.1)
clf.fit(features, target)
print('Score = ', clf.score(features, target))

Score =  0.8303533866217921


In [124]:
print(classification_report(target_test, clf.predict(features_test)))

             precision    recall  f1-score   support

        1.0       0.82      1.00      0.90      1958
        2.0       0.00      0.00      0.00       206
        3.0       0.00      0.00      0.00       198
        4.0       0.00      0.00      0.00        13
        5.0       0.00      0.00      0.00         2

avg / total       0.68      0.82      0.74      2377



C:\Users\Marine\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [127]:
#Régression logistique

cls = LogisticRegression() 
cls.fit(features_train, target_train)
predictions = cls.predict(features_test)
cls.intercept_
cls.coef_
print(confusion_matrix(target_test, predictions))

[[1958    0    0    0    0]
 [ 206    0    0    0    0]
 [ 198    0    0    0    0]
 [  13    0    0    0    0]
 [   2    0    0    0    0]]


**PROBLEME**

Le modèle prend toujours 1.0 en valeur puisqu'en prenant cette valeur il a très peu de chance de se tromper. En effet, sur 10 000 offres, 8 000 sont des CDI (soit 1.0).